version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:host-gateway"